### ISSUE TITLE
Fix broken links in documentation

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-website#16]
Migrating from [axe-core](https://github.com/dequelabs/axe-core/issues/631):

>Go to this page

>https://www.axe-core.org/docs/

>Click the link for Section 3: Examples

>Click any link in the examples paragraph and you will see it is broken

The raw link URLs in that section look like this: `[jasmine](examples/jasmine)`

The problem stems from the API docs being in a docs folder on S3, whereas for the Github version they are in a doc folder. Our build system probably needs to do a bit more to correct the links.

The table of contents link to that section at the top is also outdated on Github, it says "section-5" in it while it's really "section-3". It would be better to auto-generate those links.

**Comment by mohanraj-r** [comment]
Not sure if this is related:
Broken link: https://accessibility.deque.com/axe-core-stories
Linked from: https://github.com/dequelabs/axe-core/blob/develop/README.md

**Comment by marcysutton** [comment]
@mohanraj-r that's a different issue, I've passed it along to our marketing team. This issue can now be closed as we've migrated away from axe-core.org in favor of deque.com
