### ISSUE TITLE
Highlighter not working properly on all machines

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-website#3]
For some reason when I pulled down the site and built it with Jekyll, the highlighter was broken on the homepage and docs pages. These code blocks are indicated in Markdown with triple back-ticks and the language, such as ```javascript.

Jekyll transforms that markdown correctly into a DIV with 'highlighter-rouge' CSS classes on it, but it misses the `language-javascript` class to style the blocks properly.

I fixed this temporarily by changing the Markdown to the correct HTML structure. But this will break code snippets in the documentation when they get regenerated from Github.

Is there a gem or some install step missing?

**Comment by nschonni** [comment]
Instead of using vanilla Jekyll, https://github.com/github/pages-gem gives you the whitelisted plug-ins too (and the version running on the server)

**Comment by marcysutton** [comment]
This issue seems to be fixed since I upgraded Ruby for a separate Jekyll project, so I'll close this now.
