### ISSUE TITLE
Header obscures docs content when using table of contents links

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-website#7]
When you use an internal link on our docs page, such as "API Name: axe.configure", the fixed header causes the linked content to be cut off visually. The solve would be to add padding to the wrapper element...but this impacts the sidebar. So we have to find a padding solution that can accommodate the existing layout while making internal links visible when clicked.

![docs content cut off after jump](https://user-images.githubusercontent.com/1045233/27665074-f44974b6-5c1f-11e7-8de2-23961a881226.png)

**Comment by WilcoFiers** [comment]
This is a problem coming from Cauldron. We should see if they have a fix for this.
